"use client";
import { useMemo, useState } from "react";
import { analyzeHyster, validateHyster, type HysterData } from "@/lib/hyster";
import "./hyster.css";

const fmt = (v: number | null, digits = 2) => v === null ? "Sem dados" : v.toLocaleString("pt-BR", { maximumFractionDigits: digits });

export default function HysterDashboard() {
  const [data, setData] = useState<HysterData | null>(null);
  const [month, setMonth] = useState("all"), [asset, setAsset] = useState("all"), [error, setError] = useState("");
  const [selected, setSelected] = useState(0);
  const report = useMemo(() => data ? analyzeHyster(data, month, asset) : null, [data, month, asset]);
  const deviation = report?.deviations[selected];
  async function importFile(file?: File) {
    if (!file) return;
    try {
      if (file.size > 20 * 1024 * 1024) throw new Error("Limite de 20 MB por arquivo.");
      const parsed = validateHyster(JSON.parse(await file.text()));
      setData(parsed); setMonth("all"); setAsset("all"); setSelected(0); setError("");
    } catch (e) { setError(e instanceof Error ? e.message : "Arquivo inválido"); }
  }
  return <main className="pageShell hyster">
    <header className="hero"><div><div className="eyebrow">COPILOTO OPERACIONAL AI · HYSTER TRACKER</div><h1>Pulso <span>da operação</span></h1><p>Histórico real. Evidências para investigar. Decisão humana.</p></div><a href="/">Demonstração sintética →</a></header>
    <section className="trustBanner"><div><strong>Importar base operacional</strong><p>Selecione o JSON preparado pelo importador Hyster. O arquivo é analisado neste navegador, sem envio ao servidor. Ao recarregar, importe novamente.</p><label className="hysterUpload">Selecionar base JSON<input aria-label="Selecionar base Hyster JSON" type="file" accept=".json,application/json" onChange={e => void importFile(e.target.files?.[0])} /></label></div></section>
    {error && <p role="alert">{error}</p>}
    {!data && <article className="detailCard"><h2>Seus relatórios viram uma base de decisão</h2><p>Importe o arquivo Pulso-base-Hyster-jun-ago-2026.json entregue com a análise. Para novas extrações, use o importador documentado no README.</p><p>A visão conecta utilização diária, eventos, cadastro, KPI consolidado e qualidade dos oito relatórios. Custos, combustível e manutenção só devem orientar decisões quando a medição estiver validada.</p></article>}
    {data && report && <>
      <div className="hysterFilters"><label>Mês<select value={month} onChange={e => { setMonth(e.target.value); setSelected(0); }}><option value="all">Todo o período</option>{report.months.map(m => <option key={m.month}>{m.month}</option>)}</select></label><label>Equipamento<select value={asset} onChange={e => { setAsset(e.target.value); setSelected(0); }}><option value="all">Toda a frota</option>{data.assets.map(a => <option key={a.assetId}>{a.assetId}</option>)}</select></label><span>{data.periodStart} a {data.periodEnd} · histórico diário · sem conexão em tempo real</span></div>
      <section className="kpiGrid">{[["Chave ligada", `${fmt(report.totals.key)} h`], ["Trabalho registrado", `${fmt(report.totals.work)} h`], ["Ociosidade registrada", `${fmt(report.totals.idle)} h`], ["Ociosidade / chave", `${fmt(report.totals.idlePct)}%`]].map(([label, value]) => <article className="kpiCard" key={label}><div><span>{label}</span><strong>{value}</strong></div></article>)}</section>
      <section className="detailCard"><h2>Leitura do período</h2><p>{report.totals.records} registros equipamento-dia · {report.types["Falha do sistema"] ?? 0} registros de falha de sistema · {report.types["Impacto"] ?? 0} impactos · {report.types["Status de caminhão"] ?? 0} registros de status.</p><p>Eventos repetidos não equivalem a panes independentes. A marcação “crítica” do fornecedor não determina a prioridade do Pulso.</p></section>
      <section className="detailGrid"><article className="detailCard"><h2>Distribuição de uso</h2><div className="hysterTable"><table><thead><tr><th>Ativo</th><th>Chave (h)</th><th>Ocioso (h)</th><th>Ocioso/chave</th><th>Falhas</th><th>Impactos</th></tr></thead><tbody>{report.assets.map(a => <tr key={a.assetId}><th>{a.assetId}</th><td>{fmt(a.key)}</td><td>{fmt(a.idle)}</td><td>{fmt(a.idlePct)}%</td><td>{a.faults}</td><td>{a.impacts}</td></tr>)}</tbody></table></div><p>Diferenças de uso pedem contexto de escala, demanda e função. Não indicam, sozinhas, excesso de frota.</p></article>
      <article className="detailCard"><h2>Evolução mensal</h2><p>Comparação dos meses para o equipamento selecionado.</p>{report.months.map(m => <div className="hysterMonth" key={m.month}><span>{m.month} · {fmt(m.key)} h de chave</span><meter aria-label={`Ociosidade ${m.month}`} min={0} max={100} value={m.idlePct ?? 0} /><strong>{fmt(m.idlePct)}% ocioso/chave</strong></div>)}<p>Razões calculadas pelas somas de horas; não pela média de percentuais arredondados.</p></article></section>
      <section className="workspace"><aside className="insightsPane"><h2>Desvios para investigar</h2><p>Comparação com o próprio equipamento nos 28 dias anteriores, pelo menos 10 registros com ≥ 1 h de chave. Sinal: z ≥ 2 e aumento ≥ 10 pontos percentuais.</p><div className="insightList">{report.deviations.map((d, i) => <button className={`insightCard ${i === selected ? "selected" : ""}`} key={`${d.assetId}-${d.date}`} onClick={() => setSelected(i)}><div><strong>{d.assetId} · {d.date}</strong><p>{fmt(d.current)}% ocioso/chave · {fmt(d.z)}σ</p></div></button>)}</div>{!report.deviations.length && <p>Nenhum sinal com esses critérios. Isso não certifica a saúde dos equipamentos.</p>}</aside>
      <article className="detailPane"><h2>Copiloto · evidência e próxima ação</h2>{deviation ? <><h3>{deviation.assetId} · {deviation.date}</h3><p>Ociosidade/chave de {fmt(deviation.current)}%, contra média histórica diária de {fmt(deviation.baseline)}% em {deviation.samples} registros anteriores. Foram {fmt(deviation.idleHours)} h ociosas no dia.</p><p><strong>Investigar:</strong> confira espera por carga, abastecimento, liberação de área, escala e condição do equipamento. O desvio não identifica a causa e não atribui responsabilidade ao operador.</p><p><strong>Validar uma ação:</strong> registre a causa com a operação e acompanhe ociosidade/chave em dias com demanda comparável. Esta tela não mede ainda o efeito de intervenções.</p><small>Fonte: DailyFleetUtilization.xlsx, Folha2, linha {deviation.sourceRow}. Baseline exclusivamente anterior ao dia analisado. Regra estatística exploratória; sem previsão de pane ou probabilidade calibrada.</small></> : <p>Selecione um desvio para examinar a evidência.</p>}<hr /><h3>Investigação de eventos</h3>{report.assets.filter(a => a.faults || a.impacts).map(a => <p key={a.assetId}><strong>{a.assetId}:</strong> {a.faults} registros de falha e {a.impacts} impactos. {a.impacts ? "Revisar os impactos com segurança e manutenção. " : ""}Consultar códigos, recorrência e ordens de serviço antes de concluir a causa.</p>)}</article></section>
      <section className="detailCard"><h2>Qualidade e limites da base</h2><ul><li>{report.quality.waitAboveIdle} registros com espera maior que ociosidade; não usar “espera/ociosidade” como fração do tempo ocioso.</li><li>{report.quality.nonAdditive} registros com trabalho + ociosidade acima da chave por mais de 0,03 h. Os contadores não formam uma partição consistente.</li><li>Dias ausentes não são preenchidos com zero. Sem calendário planejado, não calculamos disponibilidade ou utilização da capacidade.</li><li>Combustível: {data.fuel.every(f => f.reportedLiters === 0) ? "relatório zerado; consumo não validado" : "registros disponíveis; validar medição"}. Sem estimativa automática de litros, CO₂ ou economia.</li><li>Custos: {data.costs.some(c => c.reportedTotal === null) ? "totais ausentes; custo não validado" : "registros disponíveis; validar moeda e cobertura"}. Manutenção: {data.maintenanceAvailable ? "registros na origem; requer integração detalhada" : "relatório sem registros"}.</li></ul><details><summary>Conciliação do período completo</summary><p>Diário: {fmt(data.daily.reduce((s, r) => s + r.keyHours, 0))} h de chave. KPI consolidado: {fmt(data.kpi.reduce((s, r) => s + r.keyHours, 0))} h. Horímetro de serviço: {fmt(data.kpi.reduce((s, r) => s + r.serviceHours, 0))} h — contador diferente da chave.</p><p>Snapshot atual, fora do histórico: {data.currentStatus.map(s => `${s.assetId}: ${s.status} (${s.lastAccess})`).join("; ")}. Não prova disponibilidade nos três meses.</p></details><details><summary>Rastreabilidade dos oito arquivos</summary>{data.sources.map(s => <p key={s.file}><strong>{s.file}</strong><br /><small>SHA-256: {s.sha256}</small></p>)}</details></section>
      <footer className="dataFooter"><p>Hyster Tracker · análise descritiva e sinais estatísticos exploratórios. Sem nomes ou cartões de operadores. Dados reais separados da demonstração sintética e do seu modelo multivariado.</p></footer>
    </>}
  </main>;
}
